modLoader="javafml"
loaderVersion="[35,)"
license="All Rights Reserved"

[[mods]]
modId="tnt"
version="2.0.0"
displayName="Custom TNT"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://enderboy2000.wixsite.com/enderboy2000"
logoFile="logo.png"
authors="EnderBoy2000; Mehmetagatr"
description='''
Adds a new fully customizable TNT to minecraft
'''

[[dependencies.tnt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




